swagger: '2.0'
info:
  title: Password Manager API
  description: Password Manager
  version: "1.0.0"
schemes:
  - https
basePath: /passwordManager
produces:
  - application/json
paths:
  /login:
    post:
      summary: Login
      description: |
        Login
      parameters:
        - name: login
          in: body
          required: true
          schema: 
            $ref: "#/definitions/Login"
      responses:
        200:
          description: Successful login
          schema:
            $ref: '#/definitions/Token'
  /validate-token:
    post:
      summary: Validate token
      description: |
        Validate token
      parameters:
        - name: token
          in: body
          description: Token
          required: true
          schema: 
            $ref: "#/definitions/Token"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/TokenWithUser"
  /accepting-new-members:
    get:
      summary: Accepting new members
      description: Accepting new members
      responses:
        200:
          description: Whether new member signups are accepted
          schema:
            $ref: "#/definitions/b"
  /get-password-details:
    post:
      summary: Get Password Details
      description: Get password details
      parameters:
        - name: token
          in: body
          schema: 
            $ref: "#/definitions/GetPasswordDetails"
          description: Get Password Details
      responses:
        200:
          description: Details of a password
          schema:
            $ref: '#/definitions/PasswordDetails'
  /delete-password:
    post:
      summary: Delete a password
      description: Delete a password
      parameters:
        - name: deletePassword
          in: body
          schema:
            $ref: "#/definitions/DeletePassword"
          description: Delete password
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Token"
  /getPasswords:
    post:
      summary: Get password list
      description: Get password list
      parameters:
        - name: token
          in: body
          schema:
            $ref: "#/definitions/Token"
          description: Token
      responses:
        200:
          description: List of passwords
          schema:
            $ref: "#/definitions/PasswordList"

  /signup:
    post:
      summary: Signup
      description: Signup
      parameters:
        - name: userDetails
          in: body
          schema:
            $ref: "#/definitions/Login"
          description: User Details
      responses:
        200:
          description: Token
          schema:
            $ref: "#/definitions/Token"
  /putPassword:
    put:
      summary: Save password
      description: Save password
      parameters:
        - name: Password Details
          in: body
          schema:
            $ref: "#/definitions/PutPassword"
          description: Password Details
      responses:
        200:
          description: Token
          schema:
            $ref: "#/definitions/PutPasswordResponse"
definitions:
  b:
    type: boolean
  Login: 
    type: object
    properties:
      username: 
        type: string
      password:
        type: string
  Token:
    type: object
    properties:
      token:
        type: string
  TokenWithUser:
    type: object
    properties:
      token:
        type: string
      user:
        type: string
      systemKey:
        type: string
        description: WTF?
  GetPasswordDetails:
    type: object
    properties:
      token:
        type: string
      passwordId:
        type: string
  PasswordDetails:
    type: object
    properties:
      token:
        type: string
      description:
        type: string
      username:
        type: string
      password:
        type: string
  DeletePassword:
    type: object
    properties:
      token:
        type: string
      passwordId:
        type: string
  PasswordList:
    type: object
    properties:
      token:
        type: string
      passwords:
        type: array
        items:
          $ref: "#/definitions/Password"
  Password:
    type: object
    properties: 
      passwordId:
        type: string
      description:
        type: string
  PutPassword:
    type: object
    properties:
      token:
        type: string
      passwordId:
        type: string
      description:
        type: string
      username:
        type: string
      password:
        type: string
  PutPasswordResponse:
    type: object
    properties:
      token: 
        type: string
      passwordId:
        type: string
